# Text-based Object Removal System Configuration File
# This configuration file manages all system parameters

# Model Configuration
models:
  # SAM (Segment Anything Model) Configuration
  sam:
    model_type: "vit_h"  # vit_h (large), vit_l (medium), vit_b (small)
    checkpoint_path: "./Inpaint-Anything/pretrained_models/sam_vit_h_4b8939.pth"
  
  # LaMa (Large Mask Inpainting) Configuration
  lama:
    config_path: "./Inpaint-Anything/lama/configs/prediction/default.yaml"
    checkpoint_path: "./Inpaint-Anything/pretrained_models/big-lama/big-lama"
  
  # GroundingDINO Configuration
  grounding_dino:
    config_path: "./models/grounding_dino/GroundingDINO_SwinT_OGC.py"
    checkpoint_path: "./models/grounding_dino/groundingdino_swint_ogc.pth"

# Processing Parameters
processing:
  # Input/Output Settings
  input_dir: "./input_image"       # Input image directory
  output_dir: "./output_image"     # Output base directory
  
  # Detection Thresholds
  box_threshold: 0.35      # Object detection confidence threshold (0.0-1.0)
  text_threshold: 0.25     # Text matching threshold (0.0-1.0)
  
  # Mask Processing
  dilate_kernel_size: 20   # Mask dilation kernel size (0 to disable)
  combine_masks: false     # Whether to combine multiple masks into one
  
  # Memory Optimization
  max_image_size: 2048     # Maximum image size (width/height limit, resize if exceeded)
  memory_scale_factor: 0.5 # Resize factor when memory is insufficient
  
  # Batch Processing Settings
  batch_processing: true   # Enable batch processing
  save_intermediate: true  # Save intermediate results (GroundingDINO detection, SAM masks)

# Device Configuration
device:
  type: "auto"  # "auto", "cuda", "cpu"
                # For auto: use "cuda" if CUDA is available, otherwise "cpu"

# Logging Configuration
logging:
  level: "WARNING"    # Log level: DEBUG, INFO, WARNING, ERROR
  
# General Configuration
general:
  # Supported Image Formats
  supported_image_formats: [".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".webp"]
  
  # Default Values (used when arguments are not specified)
  default_text_prompt: "red pylon"                 # Default text prompt
  
  # Output Directory Structure
  output_subdirs:
    grounding_dino: "GroundingDINO"   # GroundingDINO detection results
    sam: "SAM"                        # SAM mask results
    lama: "LAMA"                      # LAMA inpainting results